# Generated by Django 2.1.5 on 2019-01-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180601_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete='name', to='api.ArticleSource', verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='account',
            field=models.ForeignKey(on_delete='name', to='api.UserInfo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='content_type',
            field=models.ForeignKey(on_delete='name', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete='name', to='api.UserInfo', verbose_name='会员名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete='name', to='contenttypes.ContentType', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='p_node',
            field=models.ForeignKey(blank=True, null=True, on_delete='name', to='api.Comment', verbose_name='父级评论'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_course',
            field=models.ForeignKey(blank=True, help_text='若是学位课程，此处关联学位表', null=True, on_delete='name', to='api.DegreeCourse'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(on_delete='name', to='api.CourseSubCategory'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete='name', related_name='coursechapters', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete='name', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_detail',
            field=models.ForeignKey(on_delete='name', to='api.CourseDetail'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='chapter',
            field=models.ForeignKey(on_delete='name', related_name='coursesections', to='api.CourseChapter'),
        ),
        migrations.AlterField(
            model_name='coursesubcategory',
            name='category',
            field=models.ForeignKey(on_delete='name', to='api.CourseCategory'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='chapter',
            field=models.ForeignKey(on_delete='name', to='api.CourseChapter'),
        ),
        migrations.AlterField(
            model_name='oftenaskedquestion',
            name='content_type',
            field=models.ForeignKey(on_delete='name', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='content_type',
            field=models.ForeignKey(on_delete='name', to='contenttypes.ContentType', verbose_name='价格关联的表名称'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='degree_course',
            field=models.ForeignKey(on_delete='name', to='api.DegreeCourse'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='username',
            field=models.ForeignKey(on_delete='name', to='api.UserInfo'),
        ),
    ]
